apiVersion: apps/v1
kind: Deployment
metadata:
  name: citbot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: citbot
  template:
    metadata:
      labels:
        app: citbot
    spec:
      containers:
        - name: citbot
          image: "gitlab-registry.maruru.me/ilts/docker-ci-test:3f79bc95443fc94ca32bc4ababdca45cd47fa1e7"
          env:
            # auth
            - name: TOKEN
              valueFrom:
                secretKeyRef:
                  name: bot-secret
                  key: duscord-token
      imagePullSecrets:
        - name: gitlab-nsslums-citbot
